disabled_rules:
  - todo
  - line_length
  - identifier_name
  - type_body_length
  - file_length
  - function_body_length
  - type_name
  - nesting
  - computed_accessors_order
opt_in_rules:
  - discouraged_object_literal
  - todo
  - force_unwrapping
force_cast: error
force_try: error
force_unwrapping: error

included:
  - ViewsByCode
  - ViewsByCodeTest
excluded:
  - Pods
