disabled_rules:
  - todo
  - line_length
  - identifier_name
  - type_body_length
  - file_length
  - function_body_length
  - type_name
  - nesting
  - unneeded_notification_center_removal
opt_in_rules:
  - discouraged_object_literal
force_cast: error
force_try: error
force_unwrapping: error
todo: warning

included:
    - ViewsByCode
    - ViewsByCodeTest
excluded:
    - Pods
