disabled_rules:
  - line_length
  - identifier_name
  - type_body_length
  - file_length
  - function_body_length
  - type_name
  - nesting
opt_in_rules:
  - discouraged_object_literal
  - force_unwrapping
  - todo
force_cast: error
force_try: error
force_unwrapping: error
todo: warning

excluded:
    - Pods
